# Generated by Django 3.1.7 on 2021-02-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('idCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('rol', models.SmallIntegerField()),
                ('phoneNumber', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('eps', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('profession', models.CharField(max_length=50)),
            ],
        ),
    ]
