# Generated by Django 3.1.7 on 2021-02-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_signedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.SmallIntegerField(default=0),
        ),
    ]
